In [ ]:
import torch
torch.__version__

'2.6.0+cu124'

In [ ]:
torch.__version__

'2.6.0+cu124'

In [ ]:
scalar = torch.tensor(7)
scalar.item()

7

In [ ]:
scalar2 = torch.tensor([[[1,2], [3,4]], [[5, 6], [6, 7]]])
scalar2.tolist()

[[[1, 2], [3, 4]], [[5, 6], [6, 7]]]

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
f = torch.arange(start=0, end=10, step=1)
g = torch.zeros_like(f)
h = torch.rand(1, 5, 2)


tensor([[[0.7317, 0.2129],
         [0.6843, 0.6293],
         [0.8006, 0.6196],
         [0.6593, 0.7938],
         [0.4508, 0.5760]]])

In [ ]:
tensor = torch.rand(2, 2 ,2)
tensor = tensor * 10
tensor

tensor([[[4.8159, 7.8151],
         [9.9335, 2.4411]],

        [[7.7134, 9.2353],
         [6.3693, 3.4637]]])

In [ ]:
tensor = tensor * 10
tensor

tensor([[[481.5877, 781.5060],
         [993.3487, 244.1108]],

        [[771.3401, 923.5350],
         [636.9324, 346.3707]]])

In [ ]:
A = torch.tensor([[1, 1],
                   [2, 2]])
x = torch.tensor([ [1, 2],
                   [3, 4]])
A @ x

tensor([[ 4,  6],
        [ 8, 12]])

In [ ]:
x = torch.rand(4)
y = torch.rand(4)
torch.matmul(x, y)

tensor(2.2412)

In [ ]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
# Create a tensor
x = torch.arange(0, 2, 1)
x

tensor([0, 1])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
x = x.type(torch.float32)
torch.argmin(x)

tensor(0)

In [ ]:
torch.linalg.vector_norm(x.type(torch.float32))

tensor(1.)

In [ ]:
x = torch.arange(1, 8, dtype=torch.float32)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
another_row = torch.tensor([[8.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]])
result = torch.cat([x_unsqueezed, another_row], dim=0)
result, result.shape

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


(tensor([[1., 2., 3., 4., 5., 6., 7.],
         [8., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([2, 7]))

In [ ]:
torch.rand(1)

tensor([0.2969])

In [ ]:
torch.backends.mps.is_available()

False

In [ ]:
a = torch.rand(7,7)
a

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [ ]:
b = torch.rand(1, 7)
torch.matmul(a, torch.transpose(b, 0, 1))

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [ ]:
torch.manual_seed(0)
torch.cuda.manual_seed(1234)

In [ ]:
torch.manual_seed(1234)
x = torch.rand(2, 3)
y = torch.rand(2, 3)
x_on_t = x.to("cuda")
y_on_t = y.to("cuda")
r = torch.matmul(x_on_t, y_on_t.T)

In [ ]:
torch.max(r)

tensor(0.3647, device='cuda:0')

In [ ]:
torch.min(r)

tensor(0.3647, device='cuda:0')

In [ ]:
torch.argmax(r)

tensor(3, device='cuda:0')

In [ ]:
torch.argmin(r)

tensor(0, device='cuda:0')

In [ ]:
torch.manual_seed(7)
o = torch.rand(1, 1, 1, 10)
print(o.shape)
p = torch.squeeze(o)
print(p.shape)

torch.Size([1, 1, 1, 10])
torch.Size([10])
